// GENERATED by tools/locale, do not edit by hand.
using System.Collections.Generic;

namespace Seety.Localization
{
    /// <summary>
    /// Every language Seety ships, in one place.
    ///
    /// The list is exactly the twelve locales Cities: Skylines II itself supports - the game
    /// offers no other locale id for a player to pick, so a thirteenth table could never be
    /// reached. English is the reference: every other table carries the same keys, which the
    /// generator guarantees by emitting all twelve from one source.
    /// </summary>
    public static class LocaleTables
    {
        public static IEnumerable<LocaleTable> All()
        {
            yield return new LocaleTable(Strings.StringsEn.LocaleId, Strings.StringsEn.Table());
            yield return new LocaleTable(Strings.StringsDe.LocaleId, Strings.StringsDe.Table());
            yield return new LocaleTable(Strings.StringsEs.LocaleId, Strings.StringsEs.Table());
            yield return new LocaleTable(Strings.StringsFr.LocaleId, Strings.StringsFr.Table());
            yield return new LocaleTable(Strings.StringsIt.LocaleId, Strings.StringsIt.Table());
            yield return new LocaleTable(Strings.StringsJa.LocaleId, Strings.StringsJa.Table());
            yield return new LocaleTable(Strings.StringsKo.LocaleId, Strings.StringsKo.Table());
            yield return new LocaleTable(Strings.StringsPl.LocaleId, Strings.StringsPl.Table());
            yield return new LocaleTable(Strings.StringsPtBr.LocaleId, Strings.StringsPtBr.Table());
            yield return new LocaleTable(Strings.StringsRu.LocaleId, Strings.StringsRu.Table());
            yield return new LocaleTable(Strings.StringsZhHans.LocaleId, Strings.StringsZhHans.Table());
            yield return new LocaleTable(Strings.StringsZhHant.LocaleId, Strings.StringsZhHant.Table());
        }
    }
}
