# -*- coding: utf-8 -*-
import io, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from gen_locale import D, LOCALES, OUT
import loc_vitals   # noqa: F401  - registers its keys on import
import loc_ui       # noqa: F401

os.makedirs(OUT, exist_ok=True)

HEADER = """// GENERATED by tools/locale, do not edit by hand: every language is emitted from one table so
// that no key can exist in one and be missing from another. Edit the generator and re-run it.
using System.Collections.Generic;

namespace Seety.Localization.Strings
{
    /// <summary>%s (%s).</summary>
    public static class Strings%s
    {
        public const string LocaleId = "%s";

        public static Dictionary<string, string> Table()
        {
            return new Dictionary<string, string>
            {
"""

NAMES = {
    "En": "English", "De": "German", "Es": "Spanish", "Fr": "French", "It": "Italian",
    "Ja": "Japanese", "Ko": "Korean", "Pl": "Polish", "PtBr": "Brazilian Portuguese",
    "Ru": "Russian", "ZhHans": "Simplified Chinese", "ZhHant": "Traditional Chinese",
}


def cs(value):
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


keys = sorted(D.keys())

for i, (suffix, locale_id) in enumerate(LOCALES):
    body = []
    for k in keys:
        body.append("                { " + cs(k) + ", " + cs(D[k][i]) + " },")
    text = (HEADER % (NAMES[suffix], locale_id, suffix, locale_id)
            + "\n".join(body)
            + "\n            };\n        }\n    }\n}\n")
    with io.open(os.path.join(OUT, "Strings%s.cs" % suffix), "w", encoding="utf-8", newline="\r\n") as f:
        f.write(text)

# The registry.
tables = "\n".join(
    "            yield return new LocaleTable(Strings.Strings%s.LocaleId, Strings.Strings%s.Table());"
    % (s, s) for s, _ in LOCALES)

registry = """// GENERATED by tools/locale, do not edit by hand.
using System.Collections.Generic;

namespace Seety.Localization
{
    /// <summary>
    /// Every language Seety ships, in one place.
    ///
    /// The list is exactly the twelve locales Cities: Skylines II itself supports - the game
    /// offers no other locale id for a player to pick, so a thirteenth table could never be
    /// reached. English is the reference: every other table carries the same keys, which the
    /// generator guarantees by emitting all twelve from one source.
    /// </summary>
    public static class LocaleTables
    {
        public static IEnumerable<LocaleTable> All()
        {
%s
        }
    }
}
""" % tables

with io.open(os.path.join(os.path.dirname(OUT), "LocaleTables.cs"), "w", encoding="utf-8", newline="\r\n") as f:
    f.write(registry)

print("scritte %d lingue x %d chiavi" % (len(LOCALES), len(keys)))
